[[plugins]]
repo = 'Shougo/dein.vim'~
[[plugins]]
repo = 'Shougo/unite.vim'~
[[plugins]]
repo = 'Shougo/neocomplcache.vim'
[[plugins]]
repo = 'slimv.vim'
[[plugins]]
repo = 'https://github.com/vim-latex/vim-latex'
[[plugins]]
repo = 'Shougo/neomru.vim'
[[plugins]]
repo = 'kien/rainbow_parentheses.vim'
[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if dein#util#_is_windows()
      let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
	  let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
      let cmd = 'gmake'
   else
	    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
  '''
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'
[[plugins]]
repo = 'https://github.com/vim-ruby/vim-ruby'
[[plugins]]
repo = 'https://github.com/tpope/vim-rails/'
[[plugins]]
repo = 'https://github.com/scrooloose/nerdtree/'
[[plugins]]
repo = 'https://github.com/kovisoft/slimv/'
